spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}


#spring.application.name=restaurante
#server.port=8080

#spring.datasource.url=jdbc:mysql://localhost:3306/dbrestaurante?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=admin
#spring.datasource.password=KLCB@316junk*
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# MYSQL
## spring.jpa.hibernate.ddl-auto=update
## spring.datasource.url=jdbc:mysql://localhost:3306/dbrestaurante
## spring.datasource.username=root
## spring.datasource.password=
## spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## spring.jpa.show-sql: true
## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #  # # # # # # # # # 
#paypal.mode=sandbox
#paypal.client.id=AVDB2dG9JLwObrRlvfbnTg0KF98-g62rkTHvZStxogqD_29tEEf48hnNb8fGu80Tz2Lb-vDRQ8NOyWoZ
#paypal.client.secret=ED5KAY_xRG1xJFe1ABytjEh7ISmHn2p4zuazpn51DQ2BEzdYezAtU6uKHoeyYVPe2IXVK17HVJopPJzQ

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration